config/routes.rb
Blocipedia::Application.routes.draw do
  
  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body


def role?(base_role)
  role == base_role.to_s
end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

include Pundit

rescue_from Pundit::NotAuthorizedError do |exception|
   redirect_to root_url, alert: exception.message
 end

  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
    authorize @wikis
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(params.require(:wiki).permit(:name, :description, :public))
    authorize @wiki
    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(params.require(:wiki).permit(:name, :description, :public))
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again"
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>

      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: Star Li</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Blocipedia is a resource that allows users to create public and private Markdown-based wikis.</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Blocipedia will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Blocipedia will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Blocipedia will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Wiki#edit</h1>
<p>Find me in app/views/wiki/edit.html.erb</p>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.name, wiki %>
          </h4>
          <small>
            <%= wiki.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if policy(Wiki.new).create? %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis:</p>
    <ul>
      <li>Make sure the wiki is appropriate.</li>
      <li>Inappropriate wiki posts will be deleted.</li>
      <li>Correct changes are appreciated.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter wiki name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter wiki description" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public wiki
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<% if policy(@wiki).edit? %>
  <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<p><%= @wiki.body %></p>